### ISSUE TITLE
What does this package solve for?

### ISSUE THREAD

**Issue by randyzwitch** [davidanthoff/NodeJS.jl#11]
I'm finding that I want to add nodejs into my ECharts package, and probably Vega also at some point. What benefit does this package provide vs just checking the users environment to see if node is installed?

Wanted to make sure I wasn't missing anything before I went too far!

**Comment by davidanthoff** [comment]
The main benefit is that you insulate yourself from any weird user installations, version mismatches and all of that. This package just installs its own, private NodeJS version and makes it easy for you to run things in that private NodeJS environment from a package that uses it. Or at least that is the theory ;)

VegaLite.jl shows how to use it. There is a ``package.json`` file in the ``deps`` folder, and then ``build.jl`` calls ``npm`` to install all the npm packages that are listed in that ``package.json`` file.

And then we just run a javascript file from julia when we want to compile a vega-lite spec, that happens [here](https://github.com/fredo-dedup/VegaLite.jl/blob/master/src/show.jl#L4).

So far it seems to work pretty well, I'm not aware of any problems, issues or errors. But that might also be because very few folks have used it...

**Comment by randyzwitch** [comment]
Thanks for the background David. Makes sense, and I think I'll probably give this package a try to provide PNG support for ECharts

**Comment by davidanthoff** [comment]
Just one warning re PNG: I initially tried to use the native PNG support in the nodejs part of vega-lite, but that requires installation of the canvas npm package, and that is anything but a smooth installation experience, so it essentially was not an option. Not sure whether ECharts also relies on the npm canvas package, but if it does, it probably is not a path to a smooth installation experience.

In the end we are now using the vega-lite ability to export SVG files (which doesn't require canvas), and then use Cairo.jl and Rsvg.jl to convert to PNG, PDF etc. The binary deployment story of Cairo.jl and Rsvg.jl is not as stable as I would like it to be, but it still seems way better than the story with npm canvas.

**Comment by randyzwitch** [comment]
ECharts provides it's own PNG through its `toolbox` method. I would just be using Node as a means of programmatically pressing the download button.
